---
- name: GitHub Actions Runner
  hosts: vagrants
  become: yes
  vars:
    - runner_user: runner
  tasks:
    - name: Runner User
      user:
        name: '{{ runner_user }}'
        state: present
    - name: Setup GitHub actions runner
      include_role:
        name: monolithprojects.github_actions_runner
      vars:
        access_token: "{{ lookup('env','PAT') }}"
      tags:
        - uninstall
    - name: Setup Docker engine
      include_role:
        name: nickjj.docker
      vars:
        docker__users:
          - '{{ runner_user }}'
